name: Release Build

on:
  push:
    branches: [ main ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "neorv32/**"
      - "osflow/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Build Neorv32
        uses: docker://gcr.io/hdl-containers/impl/icestorm
        with:
          args: make GHDL_MODULE="-m ghdl" -C osflow/boards/iceduino all

      - name: Create report
        run: |
          echo osflow/boards/iceduino/yosys-report.txt >> report.txt
          echo osflow/boards/iceduino/nextpnr-report.txt >> report.txt

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            report.txt
            osflow/boards/iceduino/iceduino_impl.bin
